[project]
name = "tfg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "marimo>=0.21.1",
    "matplotlib>=3.10.8",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "plotly>=6.6.0",
    "pynei",
    "scatter3d-anywidget>=0.1.14",
    "scikit-learn>=1.7.2",
]

[tool.uv.sources]
pynei = { path = "../Jblanca/pynei", editable=true }
